In [83]:
import numpy as np 
import pandas as pd

In [84]:
df=pd.read_csv('customer.csv')
df.head(50)

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [85]:
df['education'].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [86]:
x=df.iloc[:,:4]
y=df.iloc[:,-1]

In [87]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

In [88]:
x_train.shape

(45, 4)

In [89]:
from sklearn.preprocessing import OrdinalEncoder

ordinal = OrdinalEncoder(
    categories=[
        ['School', 'UG', 'PG'],
        ['Poor', 'Average', 'Good']
    ]
)

x_train[['education', 'review']] = ordinal.fit_transform(
    x_train[['education', 'review']]
)

In [90]:
x_train.head()

    age  gender  review  education
35   74    Male     0.0        0.0
14   15    Male     0.0        2.0
49   25  Female     2.0        1.0
36   34  Female     2.0        1.0
12   51    Male     0.0        0.0

In [91]:
x_test[['education', 'review']] = ordinal.transform(
    x_test[['education', 'review']]
)

In [100]:
from sklearn.preprocessing import LabelEncoder

label= LabelEncoder()
pred=label.fit_transform(y_train)
pred

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0])

In [99]:
y_train.head()

35    Yes
14    Yes
49     No
36    Yes
12     No
Name: purchased, dtype: object

35    Yes
14    Yes
49     No
36    Yes
12     No
5     Yes
46     No
23     No
39     No
2      No
6      No
0      No
18     No
19    Yes
27     No
17    Yes
30     No
21     No
42    Yes
45    Yes
41    Yes
34     No
47    Yes
28     No
40     No
3      No
38     No
44     No
31    Yes
1      No
11    Yes
29    Yes
32    Yes
13     No
10    Yes
22    Yes
7     Yes
9     Yes
43     No
24    Yes
8      No
16    Yes
33    Yes
25     No
26     No
Name: purchased, dtype: object